name: "NIX"

# This determines when this workflow is run
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '.gitlab-ci.yml'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '*.md'
      - 'LICENSE'
      - 'pyproject.toml'
      - 'package.xml'
      - 'dependencies.rosintall'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '.gitlab-ci.yml'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '*.md'
      - 'LICENSE'
      - 'pyproject.toml'
      - 'package.xml'
      - 'dependencies.rosintall'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: [ubuntu, macos]
    name: (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
